project:
  type: website
  output-dir: docs

website:
  title: "SCI6203"
  navbar:
    right:
      - href: about.qmd
        text: À propos
      - icon: github
        href: https://github.com/RochDLY/sci6203
      - icon: twitter
        href: https://twitter.com
    left:
      - href: rendu1-YA.qmd
        text: Analyse par Yann Audin
      - href: rendu1-RD.qmd
        text: Analyse par Roch Delannay
format:
  html:
    theme: superhero
    css: styles.css
    code-fold: false



