project:
  type: website
  output-dir: docs

website:
  title: "SCI6203"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: yeti
    css: styles.css
    code-fold: false



